colors:
  # Default colors
  primary:
    background: "0x151515"
    foreground: "0xd8caac"

  # Normal colors
  normal:
    black: "0x323d43"
    red: "0xe68183"
    green: "0x80c081"
    yellow: "0xd9bb80"
    blue: "0x89beba"
    magenta: "0xd3a0bc"
    cyan: "0x87c0a5"
    white: "0xd8caac"

  # Bright colors
  bright:
    black: "0x6b828f"
    red: "0xe68183"
    green: "0x80c081"
    yellow: "0xd9bb80"
    blue: "0x89beba"
    magenta: "0xd3a0bc"
    cyan: "0x87c0a5"
    white: "0xd8caac"

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }

window:
  padding:
    x: 10
    y: 10

font:
  normal:
    family: Meslo LG S DZ Nerd Font Mono
    style: Regular

  bold:
    family: Meslo LG S DZ Nerd Font Mono
    style: Bold

  italic:
    family: Meslo LG S DZ Nerd Font Mono
    style: Italic

  bold_italic:
    family: Meslo LG S DZ Nerd Font Mono
    style: Bold Italic

  size: 12.0
  draw_bold_text_with_bright_colors: false
