#!usr/bin/zsh

function tgz {
    tar cf - $2 | pigz > $1
}
function add-alias {
    echo "\nalias $1=\"$2\"" >> $HOME/.aliases
    echo "\"$2\" aliased to $1"
    source ~/.zshrc
}

alias edit-aliases="nvim ~/.aliases; refresh"
alias edit-path="nvim ~/.path; refresh"
alias vi="nvim"
alias vim="nvim"
alias lock="i3lock -i pictures/wallpapers/mt.png"
alias refresh="source ~/.zshrc; echo \"sourced ~/.zshrc\""
alias due="task due:today"
alias vimrc="vim ~/.config/nvim/init.vim"
alias i3cfg="vim ~/.config/i3/config"
alias ts="task sync"
alias untar="tar xf"
alias zshrc="nvim ~/.zshrc; source ~/.zshrc"
alias svim="sudo -E nvim"
alias pls="sudo"
alias xinitrc="nvim ~/.xinitrc"
alias xresources="nvim ~/.Xresources; xrdb ~/.Xresources"
alias mc="minecraftd"
alias cpufreq="watch grep \\\"cpu MHz\\\" /proc/cpuinfo"
alias vimplug="nvim -c PlugInstall -c UpdateRemotePlugins -c qa!"
alias vt="nvim -c TW"
alias vpnrst="sudo systemctl restart openvpn-client@surfshark-la-udp.service"
alias wc="webcam-toggle.sh"
alias wa="/home/trevor/scripts/wa-shell.sh"
alias tmuxconf="nvim ~/.tmux.conf"
alias cpmail="(cd ~; cat .calpoly.muttrc > .muttrc; cat .base.muttrc >> .muttrc); neomutt"
alias gmail="(cd ~; cat .gmail.muttrc > .muttrc; cat .base.muttrc >> .muttrc); neomutt"
alias muttrc="nvim ~/.base.muttrc"

alias statcfg="nvim ~/.config/i3status/config"
