#!usr/bin/zsh

function tgz {
    tar cf - $2 | pigz > $1
}
function add-alias {
    echo "\nalias $1=\"$2\"" >> $HOME/.aliases
    echo "\"$2\" aliased to $1"
    source ~/.zshrc
}
function spot {
    if [ $(pgrep librespot) ]; then
        spt
    else
        librespot -n "spotify-daemon" -b 320 -c .cache/librespot --device-type avr --initial-volume 100 --backend alsa -u `pass spotify/username` -p `pass spotify/password` </dev/null &>/dev/null &
        disown %`jobs | grep librespot | grep -o -E '[0-9]+' | head -1`
        spt
    fi
}
function makepres {
    pandoc -t beamer $1 -o `echo $1 | sed s/.md/.pdf/`
}

function mupdfi {
    /usr/bin/mupdf -I $1 &
}
function mupdf {
    /usr/bin/mupdf $1 &
}
function zathura {
    /usr/bin/zathura $1 &
}
function find() {
    echo 'Use fd instead'
    echo "$@" > /dev/null
}
function peek() {
    if [ -d $1 ]; then
        ls $1
    else
        less $1
    fi
}
alias edit-aliases="nvim ~/.aliases; refresh"
alias edit-path="nvim ~/.path; refresh"
alias vi="nvim"
alias vim="nvim"
alias lock="i3lock -i pictures/wallpapers/mt.png"
alias refresh="source ~/.zshrc; echo \"sourced ~/.zshrc\""
alias due="task due:today"
alias vimrc="vim ~/.config/nvim/init.vim"
alias i3cfg="vim ~/.config/i3/config"
alias ts="task sync"
alias zshrc="nvim ~/.zshrc; source ~/.zshrc"
alias svim="sudo -E nvim"
alias pls="sudo"
alias xinitrc="nvim ~/.xinitrc"
alias xresources="nvim ~/.Xresources; xrdb ~/.Xresources"
alias mc="minecraftd"
alias cpufreq="watch grep \\\"cpu MHz\\\" /proc/cpuinfo"
alias vimplug="nvim -c PlugInstall -c UpdateRemotePlugins -c qa!"
alias vt="nvim -c TW"
alias vpnrst="sudo systemctl restart openvpn-client@surfshark-la-udp.service"
alias wa="/home/trevor/scripts/wa-shell.sh"
alias tmuxconf="nvim ~/.tmux.conf"
alias cpmail="(cd ~; cat .calpoly.muttrc > .muttrc; cat .base.muttrc >> .muttrc); neomutt"
alias gmail="(cd ~; cat .gmail.muttrc > .muttrc; cat .base.muttrc >> .muttrc); neomutt"
alias muttrc="nvim ~/.base.muttrc"
alias polycfg="nvim ~/.config/polybar/config.ini"
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias open="xdg-open"
alias mkdir="mkdir -p"
alias sd="sudo"
alias polybar-refresh="pkill polybar; ~/.config/polybar/launch.sh"
alias mpv-theater="mpv --vf-add=sub --video-rotate=90"
alias wcrec="ffmpeg -f v4l2 -video_size 640x480 -r 24 -i /dev/video0 -f alsa -ac 1 -i hw:3,0 videos/recordings/wcrec-$(date -u +"%Y-%m-%d-%H%M%S").mp4"
alias tree="tree -C"
alias wait-dropbox="while [ '$(dropbox-cli status)' != 'Up to date' ]; do sleep 60; done"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias rn='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias db='dropbox-cli'
alias dropbox='dropbox-cli'
alias zt="zathura"
alias v="nvim"
alias netrst="sudo systemctl restart NetworkManager network-online.target openvpn-client@surfshark-la-udp.service"
